### PR TITLE
doc: add initial documentation setup

### PR DESCRIPTION
**Pull request by ru-fu**
Based on the latest version of the starter pack.
The linkcheck is expected to fail for now (since the repo isn't public and there is no snap package).

### CODE REVIEW

**Review by tomponline — APPROVED** [review]

**Comment by ru-fu** [comment]
Why does this PR said that I closed it? And how do I undo this?

**Comment by MusicDin** [comment]
Not sure how to undo, but I think there should be a `revert` button

**Comment by tomponline** [comment]
> Why does this PR say that I closed it? And how do I undo this?

Yeah weird, it closed the same time i approved it - but says you did it.

**Comment by tomponline** [comment]
Maybe send up another PR ?

**Comment by ru-fu** [comment]
No, no button I can see ... let me try to open a new PR.

**Comment by ru-fu** [comment]
There we go. Had to make my fork public, and now I have a reopen button. :)

**Comment by tomponline** [comment]
Oh that is why, we just made the repo public!

**Comment by ru-fu** [comment]
https://github.com/canonical/lxd-imagebuilder/pull/48

**Pull request closed without merging**
